name: build avr32 tools

on: [workflow_dispatch]

jobs:
  package:
    runs-on: ubuntu-18.04

    steps:
    - name: build_avr32_tools
      run: |
        sudo apt-get install curl flex bison libgmp3-dev libmpfr-dev autoconf build-essential libncurses5-dev libmpc-dev unzip git
        git clone https://github.com/scanner-darkly/avr32-toolchain
        mkdir avr32-tools
        cd avr32-toolchain
        PREFIX=$HOME/avr32-tools make install-cross
        
    - uses: actions/upload-artifact@v2
      with:
        name: avr32-tools
        path: '~/avr32-tools/**/*'
